#
# This is a project Makefile. It is assumed the directory this Makefile resides in is a
# project subdirectory.
#

PROJECT_NAME := wifi-voice-clock
CFLAGS = -Wno-format-truncation

include $(IDF_PATH)/make/project.mk
